# Generated by Django 4.2.7 on 2023-11-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
    ]
