# Generated by Django 4.2.7 on 2023-11-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_master_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='phone_number',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
