# Generated by Django 4.2.7 on 2023-11-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_master_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
